create table "public"."routes" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "origin_id" bigint not null,
    "destination_id" bigint not null,
    "distance" double precision,
    "cost_per_unit" double precision,
    "transit_time" double precision,
    "user_id" uuid not null,
    "project_id" uuid not null,
    constraint "routes_pkey" primary key (id),
    constraint "routes_origin_id_fkey" foreign key (origin_id) references nodes (id) on delete cascade,
    constraint "routes_destination_id_fkey" foreign key (destination_id) references demand_points (id) on delete cascade,
    constraint "routes_project_id_fkey" foreign key (project_id) references projects (id) on delete cascade,
    constraint "routes_user_id_fkey" foreign key (user_id) references auth.users (id) on delete cascade
);

alter table "public"."routes" enable row level security;

create policy "Allow all access to own routes"
on "public"."routes"
as permissive
for all
to public
using ((auth.uid() = user_id));
