create table "public"."demand_points" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text,
    "latitude" double precision,
    "longitude" double precision,
    "demand" double precision,
    "service_level" double precision,
    "user_id" uuid not null,
    "project_id" uuid not null,
    constraint "demand_points_pkey" primary key (id),
    constraint "demand_points_project_id_fkey" foreign key (project_id) references projects (id) on delete cascade,
    constraint "demand_points_user_id_fkey" foreign key (user_id) references auth.users (id) on delete cascade
);

alter table "public"."demand_points" enable row level security;

create policy "Allow all access to own demand points"
on "public"."demand_points"
as permissive
for all
to public
using ((auth.uid() = user_id));
