create table "public"."cost_model_inputs" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" uuid not null,
    "project_id" uuid not null,
    "model_type" text not null,
    "inputs" jsonb not null,
    constraint "cost_model_inputs_pkey" primary key ("id"),
    constraint "cost_model_inputs_project_id_fkey" foreign key ("project_id") references "projects" ("id") on delete cascade,
    constraint "cost_model_inputs_user_id_fkey" foreign key ("user_id") references "auth"."users" ("id") on delete cascade
);

alter table "public"."cost_model_inputs" enable row level security;

create policy "Allow all access to own cost model inputs"
on "public"."cost_model_inputs"
as permissive
for all
to public
using ((auth.uid() = user_id));
