create table "public"."nodes" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text,
    "latitude" double precision,
    "longitude" double precision,
    "capacity" double precision,
    "fixed_cost" double precision,
    "variable_cost" double precision,
    "user_id" uuid not null,
    "project_id" uuid not null,
    constraint "nodes_pkey" primary key (id),
    constraint "nodes_project_id_fkey" foreign key (project_id) references projects (id) on delete cascade,
    constraint "nodes_user_id_fkey" foreign key (user_id) references auth.users (id) on delete cascade
);

alter table "public"."nodes" enable row level security;

create policy "Allow all access to own nodes"
on "public"."nodes"
as permissive
for all
to public
using ((auth.uid() = user_id));
